### ISSUE TITLE
Error when selecting transmembrane residues on structures without protein residues (e.g. 1BNA)

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#1316]
This happens when using  "**Residues Embedded in membrane**" selector on 1BNA or other structures without protein units

this is the trace
```
TypeError: Cannot read properties of undefined (reading 'spherePoint')
    at findProximateAxes (algorithm.js:461:55)
    at calculate (algorithm.js:152:97)
    at async Impl.eval [as f] (algorithm.js:64:16)
    at async execute (observable.js:79:21)
    at async computeAnvil (prop.js:75:12)
    at async Object.obtain (prop.js:70:25)
    at async Object.attach (custom-structure-property.js:61:43)
    at async Impl.eval [as f] (index.js:1492:13)
    at async execute (observable.js:79:21)
```

**Comment by arose** [comment]
@JonStargaryen would you mind having a look at this?

**Comment by arose** [comment]
> How about updating the isApplicable() check to ensure that at least 1 protein chain (with length >= 15) is present? I can PR that at some point.

that be great
