### ISSUE TITLE
Touch events in Canvas3D grid broken

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#1385]
When creating multiple Canvas3D objects with one Canvas3DContext, touch interaction is directed to only one of them, while mouse interaction is still directed to the canvas in which bounds the first event (a mouse down) occurs. This bug was introduced somewhere between v4.5.0 and v4.9.1. The changes that come closest to affecting this are a new kind of pixel scale synchronization in Canvas3D, but I still haven't figured out what really causes this.

**Comment by bergwerf** [comment]
I am also currently not able to run the build process. `npm run build` does not result in a `build` directory, and there is an error:
```
ERROR in ./lib/examples/alpha-orbitals/index.js + 1175 modules
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConcatenationScope.matchModuleReference (/home/herman/repos/universe/molstar/node_modules/webpack/lib/ConcatenationScope.js:132:13)
    at ConcatenatedModule.codeGeneration (/home/herman/repos/universe/molstar/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1192:41)
    at /home/herman/repos/universe/molstar/node_modules/webpack/lib/Compilation.js:3505:22
    at /home/herman/repos/universe/molstar/node_modules/webpack/lib/Cache.js:97:5
    at Hook.eval [as callAsync] (eval at create (/home/herman/repos/universe/molstar/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/home/herman/repos/universe/molstar/node_modules/webpack/lib/Cache.js:79:18)
    at ItemCacheFacade.get (/home/herman/repos/universe/molstar/node_modules/webpack/lib/CacheFacade.js:115:15)
    at Compilation._codeGenerationModule (/home/herman/repos/universe/molstar/node_modules/webpack/lib/Compilation.js:3498:9)
    at /home/herman/repos/universe/molstar/node_modules/webpack/lib/Compilation.js:3403:11
```

**Comment by bergwerf** [comment]
I was able to fix this by setting resolutionMode = 'native'. There might be something about the other mode that breaks the bounds check of the InputObserver. I don't fully understand the pixel scale story, but am I correct in assuming this is there in order to allow setting an explicit resolution to boost performance? I am mainly wondering if I should do anything else with these properties, I just want maximum resolution.

**Comment by dsehnal** [comment]
I was unable to reproduce the failing build, but I see the touch events are indeed broken. You can debug this using the "responsive design mode" in Firefox (Chrome prolly has it too):

![image](https://github.com/user-attachments/assets/1122ca88-5753-4b0b-b54f-13323de948af)

Would you care giving it a deeper examination?

**Comment by arose** [comment]
quickly, this #1386 fixes `build/tests/?name=render-structure-grid` for me (old Pixel phone)
