### ISSUE TITLE
Api for plugin cleanup?

### ISSUE THREAD

**Issue by azangru** [molstar/molstar#379]
(copied from a comment to issue https://github.com/molstar/molstar/issues/319)

I've been testing the Molstar plugin in the context of a single-page web application, following the instructions in the [docs](https://molstar.org/docs/plugin/). When I switch from a view that creates a new `PluginContext` instance, to a different view, and then back, I am seeing signs that the previous instance of the plugin has not been cleaned up:

1. The following warning appears in the console:

```
Symbol 'computed.accessible-surface-area.is-buried' already added. Call removeSymbol/removeCustomProps re-adding the symbol.
```

2. Resizing the viewport prints the following error:

```
Uncaught (in promise) Error: empty textures are not allowed
    at Object.define (texture.ts:264:19)
    at PostprocessingPass2.setSize (postprocessing.ts:362:35)
    at DrawPass2.setSize (draw.ts:161:33)
    at Passes2.updateSize (passes.ts:26:19)
    at handleResize (canvas3d.ts:679:20)
    at render (canvas3d.ts:380:17)
    at draw (canvas3d.ts:426:17)
    at Object.tick (canvas3d.ts:446:13)
    at PluginAnimationLoop2.<anonymous> (animation-loop.ts:21:31)
    at step (tslib.es6.js:102:23)
```

Screen capture:

https://user-images.githubusercontent.com/6834224/154852039-573f4046-55dd-4695-9491-60a48336e5e9.mp4

What's the proper way of cleaning up / destroying / discarding a plugin instance to avoid the above errors and memory leaks?

**Comment by azangru** [comment]
As a follow-up: the `empty textures are not allowed` error goes away if I run `plugin.canvas3dContext?.dispose();` during the cleanup phase. The "symbol already added" warning still shows up.

**Comment by azangru** [comment]
So sorry, I've finally found the relevant line in the docs — it's `plugin.dispose()`. After running it, both the error and the warning go away. I'll close this issue now. Sorry for the noise.
