### ISSUE TITLE
How do you remove the axes in the bottom left corner?

### ISSUE THREAD

**Issue by samirelanduk** [molstar/molstar#390]
It's nice to have sometimes, but when the plugin is quite small it takes up a lot of relative space.

**Comment by dsehnal** [comment]
``this.plugin.canvas3d?.setProps({ camera: { helper: { axes: { name: 'off', params: {} } } } });``

**Comment by samirelanduk** [comment]
Thanks, that works, but if you want to turn them back on, I assumed you could do the same but with `'on'`, but I get the following error if I do:

```
index.js:11295 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at hashString (index.js:11295:1)
    at defineValueHash (index.js:41180:1)
    at index.js:41215:1
    at Array.forEach (<anonymous>)
    at attribute (index.js:41215:1)
    at Object.get (index.js:41014:1)
    at Object.program (index.js:41229:1)
    at createProgramVariant (index.js:43702:1)
    at createRenderItem (index.js:43756:1)
    at createGraphicsRenderItem (index.js:43719:1)
    at MeshRenderable (index.js:44020:1)
    at createRenderable (index.js:44149:1)
    at add (index.js:79647:1)
    at commit (index.js:79693:1)
    at Object.commit (index.js:79755:1)
    at index.js:82146:1
    at produce (index.js:18396:1)
    at CameraHelper.setProps (index.js:82137:1)
    at Object.setProps (index.js:83185:1)
    at _callee$ (index.js:118854:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:293:1)
    at Generator.next (runtime.js:118:1)
    at asyncGeneratorStep (index.js:8:1)
    at _next (index.js:30:1)```

**Comment by dsehnal** [comment]
Yeah in that case you need to provide the params for that. Try ``ParamDefinition.getDefaultValues(CameraHelperParams).axes`` to turn them back on.

**Comment by samirelanduk** [comment]
Thanks!
