### ISSUE TITLE
Could not find node 'model'. 

### ISSUE THREAD

**Issue by nabilr** [molstar/molstar#905]
My code 
if (this.loadedParams.pdbId !== pdbId || this.loadedParams.format !== format) {
            // remove current whole tree
            await PluginCommands.State.RemoveObject(this.plugin, { state, ref: state.tree.root.ref });
            const modelTree = this.model(this.download(state.build().toRoot(), url, isBinary, pdbId.toUpperCase()), format);
           
            console.log(this.plugin.state.data,modelTree )    
            await this.applyState(modelTree); 
            console.log(this.plugin.state.data)    
                      
            const structureTree = this.structure(assemblyId);
            await this.applyState(structureTree);
        } 

always fails at 
ERROR
Could not find node 'model'.
    at new To (http://localhost:3000/static/js/bundle.js:207319:15)
    at Root.to (http://localhost:3000/static/js/bundle.js:207287:14)
    at MolStarWrapper.structure (http://localhost:3000/static/js/bundle.js:2808:38)
    at MolStarWrapper.load (http://localhost:3000/static/js/bundle.js:2183:34)

**Comment by nabilr** [comment]
when I down graded react from 18 to 17 it works
